open_base:

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100

    back_left_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_back_left_joint
        pid: {p: 1, i: 0.0, d: 0.0}

    back_right_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_back_right_joint
        pid: {p: 1, i: 0.0, d: 0.0}

    front_right_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_front_right_joint
        pid: {p: 1, i: 0.0, d: 0.0}

    front_left_joint_velocity_controller:
        type: velocity_controllers/JointVelocityController
        joint: rim_front_left_joint
        pid: {p: 1, i: 0.0, d: 0.0}

    # gazebo_ros_control/pid_gains:
    #     rim_left_joint/p: 1
    #     rim_right_joint/p: 1
    #     rim_back_joint/p: 1
    #     rim_front_joint/p: 1
